apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user-managment
  name: user-managment
spec:
  ports:
    - name: "3001"
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: user-managment
  type: NodePort
status:
  loadBalancer: {}
